application:
  subdomain: octopus
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://octopus:8080/
services:
  octopus:
    #  ghcr.io/bestruirui/octopus:v0.9.14
    # upstream: ghcr.io/bestruirui/octopus:v0.12.0
    image: registry.lazycat.cloud/czyt/bestruirui/octopus:7e05595a223a1d82
    binds:
      - /lzcapp/var/data:/app/data
