min_os_version: 1.3.8
name: Octopus
package: community.lazycat.app.octopus
version: 0.2.1
description: "为个人打造的简单、美观、优雅的 LLM API 聚合与负载均衡服务"
homepage: https://github.com/bestruirui/octopus
author: bestruirui
application:
  subdomain: octopus
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://octopus:8080/

services:
  octopus:
    # bestrui/octopus:v0.2.1
    image: registry.lazycat.cloud/czyt/bestrui/octopus:a297b943b087f997
    container_name: octopus
    binds:
      - /lzcapp/var/data:/app/data

locales:
  zh:
    name: "Octopus"
    description: "为个人打造的简单、美观、优雅的 LLM API 聚合与负载均衡服务"
  en:
    name: "Octopus"
    description: "A simple, beautiful, and elegant LLM API aggregation and load balancing service tailored for individuals"
